export enum Actions {
     LOGIN_SUCCESS = "LOGIN_SUCCESS",
     LOGIN_START = "LOGIN_START",
     REFRESH_TOKEN = "REFRESH_TOKEN",
     LOGIN_FAILURE = "LOGIN_FAILURE",

     UPDATE_GAMES_LIST = "UPDATE_GAMES_LIST",
     UPDATE_GAMES_LIST_FAILURE = "UPDATE_GAMES_LIST_FAILURE",

     JOIN_GAME_SERVER = "JOIN_GAME_SERVER",
     ESTABLISH_GAME_SERVER_CONNECTION = "ESTABLISH_GAME_SERVER_CONNECTION",
     ENTER_GAME = "ENTER_GAME",
     CONNECTION_ERROR= "CONNECTION_ERROR",

     UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS",
     SET_NOTIFICATIONS_ENABLED = "SET_NOTIFICATIONS_ENABLED",
     SET_NOTIFICATION_TYPE_ENABLED = "SET_NOTIFICATION_TYPE_ENABLED",
     UPDATE_LAST_FETCH_DATE = "UPDATE_LAST_FETCH_DATE",
     UPDATE_NOTIFICATIONS_ERROR = "UPDATE_NOTIFICATIONS_ERROR",

     UPDATE_STATIONS = "UPDATE_STATIONS",
     UPDATE_STATIONS_ERROR = "UPDATE_STATIONS_ERROR",

     UPDATE_ALLIANCE = "UPDATE_STATIONS",
     UPDATE_ALLIANCE_ERROR = "UPDATE_STATIONS_ERROR",
}

