export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_START = "LOGIN_START";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const UPDATE_GAMES_LIST = "UPDATE_GAMES_LIST";
export const UPDATE_GAMES_LIST_FAILURE = "UPDATE_GAMES_LIST_FAILURE";

export const JOIN_GAME_SERVER = "JOIN_GAME_SERVER";
export const ESTABLISH_GAME_SERVER_CONNECTION = "ESTABLISH_GAME_SERVER_CONNECTION";
export const ENTER_GAME = "ENTER_GAME";
export const CONNECTION_ERROR= "CONNECTION_ERROR";

export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";
export const SET_NOTIFICATIONS_ENABLED = "SET_NOTIFICATIONS_ENABLED";
export const SET_NOTIFICATION_TYPE_ENABLED = "SET_NOTIFICATION_TYPE_ENABLED";
export const UPDATE_LAST_FETCH_DATE = "UPDATE_LAST_FETCH_DATE";
export const UPDATE_NOTIFICATIONS_ERROR = "UPDATE_NOTIFICATIONS_ERROR";

export const UPDATE_STATIONS = "UPDATE_STATIONS";
export const UPDATE_STATIONS_ERROR = "UPDATE_STATIONS_ERROR";

